language: objective-c
osx_image: xcode9.2

before_install:
- gem install xcpretty
- gem install cocoapods
- pod install

script:
- xcodebuild -workspace talk -scheme talk -destination
  'platform=iOS Simulator,name=iPhone 6s,OS=9.2' test | xcpretty
